apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lvmlockd
  namespace: openshift-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:openshift:scc:lvmlockd
subjects:
  - kind: ServiceAccount
    name: lvmlockd
    namespace: openshift-storage
